import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel='icon' href='./fv-icon.png' />
        <title>Panaverse DAO</title>
      </head>
      <body>{children}</body>
    </html>
  )
}
